### ISSUE TITLE
RunTimeException not caught 

### ISSUE THREAD

**Issue by FergusMok** [AY2122S1-CS2103-W14-3/tp#129]
Currently, none of the RunTimeExceptions are being caught to be handled gracefully. Any of these exceptions will immediately crash the application. 

![image](https://user-images.githubusercontent.com/10182564/139284571-c9eeb33e-ed95-4043-8d0e-5ef86a0bfd92.png)

**Comment by caipng** [comment]
These exceptions should subclass `CommandException` to be caught properly

**Comment by caipng** [comment]
These exceptions correspond to their `*UniqueList`, and is not exposed to the user.
