### ISSUE TITLE
[PE-D] Unable to change status of assignment without using the grade command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-W14-3/tp#167]
Since there is an entry in the assignment list to show the status of each assignment, should there be another way for the user to change the status from NOT_SUBMITTED to SUBMITTED

![image.png](https://raw.githubusercontent.com/IceWizard4902/ped/main/files/0ffeb3c6-c66b-46fd-bd2e-363e2a029873.png)

Also, should the `grade` command automatically set the status to GRADED?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: IceWizard4902/ped#6

**Comment by marcusc55** [comment]
This is the intended behaviour. The `grade` command is used to change the status from not submitted to submitted.
