### ISSUE TITLE
[PE-D] 'rm' command not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-W14-3/tp#174]
![image.png](https://raw.githubusercontent.com/Moley456/ped/main/files/f969dfb5-4998-4fac-ad35-06dc35fef124.png)

Not sure what's the issue here but I'm unable to remove a contact from a particular module and class. Might be an error on my part? Although the parameters all seem correct to me.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Moley456/ped#6

**Comment by chaiwanlin** [comment]
Same as #176
