### ISSUE TITLE
ModuleSet not interacting with mv and rm 

### ISSUE THREAD

**Issue by FergusMok** [AY2122S1-CS2103-W14-3/tp#206]
1. Unable to move a person to another class, if he already has 1 class in the module.
![image](https://user-images.githubusercontent.com/10182564/140611809-0b9426b5-4c72-4db3-8400-fe838cf4b956.png)

2. Removing all the classes from a person's module leaves the data in this state. 
![image](https://user-images.githubusercontent.com/10182564/140611815-ee5d18cb-0b2a-4fe2-ac6d-f1c3848e2657.png)

**Comment by caipng** [comment]
@FergusMok does https://github.com/AY2122S1-CS2103-W14-3/tp/pull/207 close this?

**Comment by chaiwanlin** [comment]
@caipng yessir it does
