### ISSUE TITLE
Add search based on criteria

### ISSUE THREAD

**Issue by FergusMok** [AY2122S1-CS2103-W14-3/tp#3]
### User Story

As a user, I can search for all students with a certain weak point, so that I can offer additional help and tailor my teaching to them.

As a user, I can search for all students with a certain strong point, so that I can send them more challenging exercises that are not in the syllabus.

As an experienced user, I can find all students having a grade above/below a certain point, so that I can identify which students do well/badly for each assignment/assessment.

**Comment by caipng** [comment]
This is good to have, but not crucial to our app. Closing due to lack of time to implement.
