### ISSUE TITLE
Enhance Adding Student 

### ISSUE THREAD

**Issue by FergusMok** [AY2122S1-CS2103-W14-3/tp#38]
The current command syntax for adding a student is `add n/NAME p/PHONE e/EMAIL a/ADDRESS [t/TAG]...`
For example, `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`.

The feature enhancement should have the program prompting users, field by field, after pressing enter.
`add
Name:
Phone Number:
Email:
Address:
`

Related to #12

**Comment by caipng** [comment]
This is good to have, but not crucial to our app. Closing due to lack of time to implement.
